### PR TITLE
Add coverage check to GitHub Action and README

### LINKED ISSUE #37: Configure code coverage service w/ pytest
@tunetheweb set up coverage support in #29 but as far as i can tell we haven't changed the CICD pipeline to do anything with it:

https://github.com/sqlfluff/sqlfluff-online/blob/master/.github/workflows/push.yaml#L24

Might be fun to show our 100% via codecov badge or something!

### PR DESCRIPTION
**Pull request by tunetheweb**
Fixes #37 

Also renames `readme.md` to `README.md` for consistency.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Added some MOAR BADGES!:

image

**Comment by nolanbconaway** [comment]
Lol aight cool, so it seems like the choices are:

1. allow code coverage below 100% for those hard-to-test lines
2. enforce 100% but use pragmas to skip over hard-to-test lines

It doesn't matter a great deal to me but i wonder if anyone in @sqlfluff/sqlfluff-maintainers has strong feelings about which makes more sense! 

This PR implements option 2 nicely, so under the assumption there are no strong feelings in the group then we're good for a merge.

**Comment by tunetheweb** [comment]
FYI, this was accepted as the way forward for the main sqlfluff code and merged in https://github.com/sqlfluff/sqlfluff/pull/1346

And it's an even easier conversation here since there are no pragmas needed (we actually **do** have 100% coverage as far as pytest is concerned). But point taken that might not always be the case so good to agree the general approach.

**Comment by nolanbconaway** [comment]
Aight cool lets mergggee it!

**Comment by nolanbconaway** [comment]
Nice work crushing these issues !!

**Pull request merged**
