### PR TITLE
Send runtime error to the frontend

### PR DESCRIPTION
**Pull request by greg-finley**
Closes https://github.com/sqlfluff/sqlfluff-online/issues/358

Open to other ideas as well

Screenshot 2024-05-15 at 1 11 23 PM

### CODE REVIEW

**Review by nolanbconaway — APPROVED** [review]
I think this approach makes sense! But is RuntimeError the correct level of specificity? 

I wonder if the app should have a handler for generic errors that might not be Runtime; in which case maybe the better approach could look like a broad [error handler](https://flask.palletsprojects.com/en/3.0.x/errorhandling/#error-handlers) which returns an error page that contains exception info and maybe a like to the sqlfluff issues page.

That second option seems like more code to write, so in the meantime i think we should merge in your changes. I can set up an issue and work on it this weekend if you think the error page idea makes sense.

**Comment by greg-finley** [comment]
It's up to you! I just reached for this solution to give you similar text to what the CLI would give you, which has actionable steps.

I'm actually not sure the enumeration of possible errors beyond `RuntimeError` but it's only one I've seen raised by `lint`.

I'm happy to live with this PR or let you do a different solution.

**Comment by nolanbconaway** [comment]
Ok! Lets get this in and i'll toy with an error page later on.

**Comment by nolanbconaway** [comment]
https://github.com/sqlfluff/sqlfluff-online/issues/360

**Pull request merged**
